map:
  SMOOTH_BRICK: STONE_BRICKS
  LOG|0: OAK_LOG
  LOG|1: SPRUCE_LOG
  LOG|2: BIRCH_LOG
  LOG|3: JUNGLE_LOG
  WOOD|0: OAK_PLANKS
  WOOD|1: SPRUCE_PLANKS
  WOOD|2: BIRCH_PLANKS
  WOOD|3: JUNGLE_PLANKS
  WOOD|4: ACACIA_PLANKS
  WOOD|5: DARK_OAK_PLANKS
  WOOD_STEP|0: OAK_SLAB
  WOOD_STEP|1: SPRUCE_SLAB
  WOOD_STEP|2: BIRCH_SLAB
  WOOD_STEP|3: JUNGLE_SLAB
  WOOD_STEP|4: ACACIA_SLAB
  WOOD_STEP|5: DARK_OAK_SLAB
  STEP|0: STONE_SLAB
  STEP|1: SANDSTONE_SLAB
  STEP|3: COBBLESTONE_SLAB
  STEP|4: BRICK_SLAB
  STEP|5: SMOOTH_STONE_SLAB
  STEP|6: NETHER_BRICK_SLAB
  STEP|7: QUARTZ_SLAB
  STONE_SLAB2: RED_SANDSTONE_SLAB
  SANDSTONE|1: CHISELED_SANDSTONE
  SANDSTONE|2: CUT_SANDSTONE
  RED_SANDSTONE|1: RED_CHISELED_SANDSTONE
  RED_SANDSTONE|2: RED_CUT_SANDSTONE