map:
  STONE_BRICKS: SMOOTH_BRICK
  OAK_LOG: LOG|0
  SPRUCE_LOG: LOG|1
  BIRCH_LOG: LOG|2
  JUNGLE_LOG: LOG|3
  OAK_PLANKS: WOOD|0
  SPRUCE_PLANKS: WOOD|1
  BIRCH_PLANKS: WOOD|2
  JUNGLE_PLANKS: WOOD|3
  ACACIA_PLANKS: WOOD|4
  DARK_OAK_PLANKS: WOOD|5
  OAK_SLAB: WOOD_STEP|0
  SPRUCE_SLAB: WOOD_STEP|1
  BIRCH_SLAB: WOOD_STEP|2
  JUNGLE_SLAB: WOOD_STEP|3
  ACACIA_SLAB: WOOD_STEP|4
  DARK_OAK_SLAB: WOOD_STEP|5
  STONE_SLAB: STEP|0
  SANDSTONE_SLAB: STEP|1
  COBBLESTONE_SLAB: STEP|3
  BRICK_SLAB: STEP|4
  SMOOTH_STONE_SLAB: STEP|5
  NETHER_BRICK_SLAB: STEP|6
  QUARTZ_SLAB: STEP|7
  RED_SANDSTONE_SLAB: STONE_SLAB2
  CHISELED_SANDSTONE: SANDSTONE|1
  CUT_SANDSTONE: SANDSTONE|2
  RED_CHISELED_SANDSTONE: RED_SANDSTONE|1
  RED_CUT_SANDSTONE: RED_SANDSTONE|2
  
