map:
  STONE_BRICKS: SMOOTH_BRICK
  OAK_LOG: LOG|0
  SPRUCE_LOG: LOG|1
  BIRCH_LOG: LOG|2
  JUNGLE_LOG: LOG|3
  OAK_PLANKS: WOOD|0
  SPRUCE_PLANKS: WOOD|1
  BIRCH_PLANKS: WOOD|2
  JUNGLE_PLANKS: WOOD|3
  ACACIA_PLANKS: WOOD|4
  DARK_OAK_PLANKS: WOOD|5
  OAK_SLAB: WOOD_STEP|0
  SPRUCE_SLAB: WOOD_STEP|1
  BIRCH_SLAB: WOOD_STEP|2
  JUNGLE_SLAB: WOOD_STEP|3
  ACACIA_SLAB: WOOD_STEP|4
  DARK_OAK_SLAB: WOOD_STEP|5
  STONE_SLAB: STEP|0
  SANDSTONE_SLAB: STEP|1
  COBBLESTONE_SLAB: STEP|3
  BRICK_SLAB: STEP|4
  SMOOTH_STONE_SLAB: STEP|5
  NETHER_BRICK_SLAB: STEP|6
  QUARTZ_SLAB: STEP|7
  RED_SANDSTONE_SLAB: STONE_SLAB2
  DOUBLE_OAK_SLAB: DOUBLE_STEP|0
  DOUBLE_SPRUCE_SLAB: DOUBLE_STEP|1
  DOUBLE_BIRCH_SLAB: DOUBLE_STEP|2
  DOUBLE_JUNGLE_SLAB: DOUBLE_STEP|3
  DOUBLE_ACACIA_SLAB: DOUBLE_STEP|4
  DOUBLE_DARK_OAK_SLAB: DOUBLE_STEP|5
  DOUBLE_STONE_SLAB: DOUBLE_STEP|0
  DOUBLE_SANDSTONE_SLAB: DOUBLE_STEP|1
  DOUBLE_COBBLESTONE_SLAB: DOUBLE_STEP|3
  DOUBLE_BRICK_SLAB: DOUBLE_STEP|4
  DOUBLE_SMOOTH_STONE_SLAB: DOUBLE_STEP|5
  DOUBLE_NETHER_BRICK_SLAB: DOUBLE_STEP|6
  DOUBLE_QUARTZ_SLAB: DOUBLE_STEP|7
  DOUBLE_RED_SANDSTONE_SLAB: DOUBLE_STONE_SLAB2
  OAK_STAIRS: WOOD_STAIRS
  SPRUCE_STAIRS: SPRUCE_WOOD_STAIRS
  BIRCH_STAIRS: BIRCH_WOOD_STAIRS
  JUNGLE_STAIRS: JUNGLE_WOOD_STAIRS
  ACACIA_STAIRS: ACACIA_WOOD_STAIRS
  DARK_OAK_STAIRS: DARK_OAK_WOOD_STAIRS
  STONE_BRICK_STAIRS: SMOOTH_STAIRS
  CHISELED_SANDSTONE: SANDSTONE|1
  CUT_SANDSTONE: SANDSTONE|2
  RED_CHISELED_SANDSTONE: RED_SANDSTONE|1
  RED_CUT_SANDSTONE: RED_SANDSTONE|2
